version: "3.5"

services:
  db:

    image: postgres:alpine
    container_name: mlm-bot-postgres
    environment:
      - POSTGRES_PASSWORD=password


  redis_db:
    image: redis
    container_name: mlm-bot-redis
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]
    expose:
      - 6379

  web:
    build: .
    command: bash -c "service nginx start && gunicorn core.wsgi:application --bind 0.0.0.0:8020"
    container_name: mlm-bot-web
    restart: unless-stopped
    volumes:
      - .:/code
      - ./etc:/etc/nginx/conf.d
      - ./static:/var/www/static
      - ./media:/var/www/media
      - ./certificate:/var/www/certificate
    depends_on:
      - db
    networks:
      - default
    environment:
      DJANGO_SETTINGS_MODULE: "core.settings"
    ports:
      - "8020:8020"
      - "8021:8021"
      - "443:443"


  bot:
    build: .
    command: bash -c "python bot.py"
    container_name: mlm-bot
    restart: unless-stopped
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - default
    environment:
      DJANGO_SETTINGS_MODULE: "core.settings"

  celery_worker:
    build: .
    restart: always
    command: bash -c "celery -A workers.celery_worker.celery worker --concurrency=8 --loglevel=info"
    volumes:
      - .:/code
    depends_on:
      - redis_db
      - db
    environment:
      DJANGO_SETTINGS_MODULE: "core.settings"
      DB_NAME: "postgres"
      DB_HOST: "db"
      REDIS_HOST: "redis_db"
